### ISSUE TITLE
bug: panic when running with water-rs

### ISSUE THREAD

**Issue by gaukas** [refraction-networking/watm#2]
Getting `panic: runtime error: nil pointer dereference` when getting a connection in the Listener mode. The issue has been identified caused by the usage of the global default logger from the `log` package. And if we initialize a customized logger first and use that, everything worked perfectly. Investigations are underway for the issue of the default logger (since it worked with the Go runtime).

----

This issue is migrated from [gaukas/watm#10](https://github.com/gaukas/watm/issues/10).

**Comment by erikziyunchi** [comment]
Solved with https://github.com/refraction-networking/water-rs/pull/37
